#!/bin/sh
# autopkgtest check: Build and run a program against gz-transport, to verify that the
# headers and pkg-config file are installed correctly
# (C) 2012 Jose Luis Rivero
# Author: Jose Luis Rivero <jrivero@osrfoundation.org>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > gztest.cc
#include <gz/transport.hh>

int main()
{
    // Create a transport node.
    gz::transport::Uuid uuid;
    return 0;
}
EOF

g++ -o gztest gztest.cc `pkg-config --cflags --libs gz-transport`
echo "build: OK"
[ -x gztest ]
./gztest
echo "run: OK"

cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.22.1)

project(gz_test VERSION 1.0.0)

find_package(gz-transport REQUIRED)
add_executable(gztest gztest.cc)
target_link_libraries(gztest
   PUBLIC
      gz-transport::gz-transport)
EOF

cmake .
echo "configure cmake with component: OK"
make
echo "build cmake component:OK"
[ -x gztest ]
./gztest
echo "run: OK"
